import React, { useState, useEffect, useCallback } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { FileText, Mail, Download, AlertCircle, RefreshCw, Plus } from 'lucide-react';
import { coverageService } from '@/services';
import { useRuleSets } from '@/hooks/useRuleSets';
import { useAppContext } from '@/contexts/AppContext';
import type { CoverageReportResponse, RuleCoverageDto } from '@/types/api.types';

interface CoverageProps {
  onNavigate: (page: string, params?: { scenarioId?: string; simulationId?: string }) => void;
}

export function Coverage({ onNavigate }: CoverageProps) {
  const { addNotification } = useAppContext();

  // State
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [coverageReport, setCoverageReport] = useState<CoverageReportResponse | null>(null);
  const { ruleSetIds: availableRuleSets } = useRuleSets();
  const [selectedRuleSet, setSelectedRuleSet] = useState<string>('');
  const [trendData, setTrendData] = useState<Array<{ date: string; coverage: number }>>([]);

  // Set default selected rule set when rule sets are loaded
  useEffect(() => {
    if (availableRuleSets.length > 0 && !selectedRuleSet) {
      setSelectedRuleSet(availableRuleSets[0]);
    }
  }, [availableRuleSets, selectedRuleSet]);

  // Load coverage report
  const loadCoverage = useCallback(async () => {
    if (!selectedRuleSet) return;

    setLoading(true);
    try {
      const report = await coverageService.getLatest(selectedRuleSet);
      setCoverageReport(report);

      // Load trend data
      const trends = await coverageService.getTrends(selectedRuleSet, 30);
      setTrendData(trends.map(t => ({
        date: new Date(t.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
        coverage: t.coveragePercentage,
      })));
    } catch (e) {
      // If no report exists, that's ok
      setCoverageReport(null);
      setTrendData([]);
    } finally {
      setLoading(false);
    }
  }, [selectedRuleSet]);

  useEffect(() => {
    if (selectedRuleSet) {
      loadCoverage();
    }
  }, [selectedRuleSet, loadCoverage]);

  // Generate new coverage report
  const handleGenerateReport = async () => {
    if (!selectedRuleSet) return;

    setGenerating(true);
    try {
      const report = await coverageService.generate(selectedRuleSet);
      setCoverageReport(report);
      addNotification({
        type: 'success',
        title: 'Report Generated',
        message: `Coverage report for ${selectedRuleSet} has been generated`,
      });
      loadCoverage();
    } catch (e) {
      addNotification({
        type: 'error',
        title: 'Generation Failed',
        message: e instanceof Error ? e.message : 'Failed to generate coverage report',
      });
    } finally {
      setGenerating(false);
    }
  };

  // Export functions
  const handleExportJSON = () => {
    if (!coverageReport) return;

    const blob = new Blob([JSON.stringify(coverageReport, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `coverage-${selectedRuleSet}-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = () => {
    if (!coverageReport?.ruleCoverage) return;

    const headers = ['Rule Name', 'Rule Description', 'Covered', 'Execution Count', 'Last Executed', 'Agenda Group'];
    const rows = coverageReport.ruleCoverage.map(r => [
      r.ruleName,
      r.ruleDescription || '',
      r.covered ? 'Yes' : 'No',
      r.executionCount?.toString() || '0',
      r.lastExecutedAt || 'Never',
      r.agendaGroup || 'Default',
    ]);

    // Add summary section at the end
    const summaryRows = [
      [],
      ['=== COVERAGE SUMMARY ==='],
      ['Total Simulations', coverageReport.totalSimulations?.toString() || '0'],
      ['Total Scenarios', coverageReport.totalScenarios?.toString() || '0'],
      ['Average Executions', coverageReport.avgRuleExecutions?.toFixed(2) || '0.00'],
      ['Coverage Percentage', `${coverageReport.coveragePercentage?.toFixed(2) || '0.00'}%`],
      ['Generated At', new Date(coverageReport.generatedAt).toLocaleString()],
      ['Generated By', coverageReport.generatedBy],
    ];

    const csvContent = [headers, ...rows, ...summaryRows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `coverage-${selectedRuleSet}-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Calculate stats from report
  const overallCoverage = coverageReport?.coveragePercentage || 0;
  const totalRules = coverageReport?.totalRules || 0;
  const testedRules = coverageReport?.testedRules || 0;
  const untestedCount = totalRules - testedRules;

  // Group rules by status
  const coveredRules = coverageReport?.ruleCoverage?.filter(r => r.covered) || [];
  const lowCoverageRules = coverageReport?.ruleCoverage?.filter(r => r.covered && (r.executionCount || 0) < 5) || [];
  const untestedRules = coverageReport?.ruleCoverage?.filter(r => !r.covered) || [];

  // Heatmap data
  const heatmapData = coverageReport?.ruleCoverage?.slice(0, 10).map(r => ({
    rule: r.ruleName,
    hits: r.executionCount || 0,
    status: !r.covered ? 'untested' : (r.executionCount || 0) < 5 ? 'low' : 'covered',
    color: !r.covered ? '#E9ECEF' : (r.executionCount || 0) < 5 ? '#F7EA73' : '#285A84',
  })) || [];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <h1>Coverage Report</h1>
        <div className="flex items-center gap-3">
          <select
            value={selectedRuleSet}
            onChange={(e) => setSelectedRuleSet(e.target.value)}
            className="px-4 py-2 border rounded focus:outline-none focus:border-[var(--color-primary)] transition-colors"
            style={{ borderColor: 'var(--color-border)', fontSize: '14px', backgroundColor: 'var(--color-surface)', color: 'var(--color-text-primary)' }}
          >
            {availableRuleSets.length === 0 ? (
              <option value="">No rule sets available</option>
            ) : (
              availableRuleSets.map(rs => (
                <option key={rs} value={rs}>{rs}</option>
              ))
            )}
          </select>
          <button
            onClick={handleGenerateReport}
            disabled={generating || !selectedRuleSet}
            className="flex items-center gap-2 px-4 py-2 bg-[var(--color-primary)] text-white rounded hover:bg-[#1D4261] transition-colors disabled:opacity-50"
            style={{ fontSize: '14px', fontWeight: 500 }}
          >
            <RefreshCw size={18} className={generating ? 'animate-spin' : ''} />
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <RefreshCw className="animate-spin" size={24} style={{ color: 'var(--color-primary)' }} />
          <span className="ml-2" style={{ color: 'var(--color-text-secondary)' }}>Loading coverage data...</span>
        </div>
      ) : !coverageReport ? (
        <div className="bg-[var(--color-background)] rounded-lg p-12 text-center" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
          <AlertCircle size={48} style={{ color: 'var(--color-text-muted)', margin: '0 auto 16px' }} />
          <p style={{ color: 'var(--color-text-secondary)', fontSize: '16px', marginBottom: '16px' }}>
            No coverage report available for this rule set
          </p>
          <button
            onClick={handleGenerateReport}
            disabled={generating || !selectedRuleSet}
            className="px-6 py-2 bg-[var(--color-primary)] text-white rounded hover:bg-[#1D4261] transition-colors disabled:opacity-50"
            style={{ fontSize: '14px' }}
          >
            Generate First Report
          </button>
        </div>
      ) : (
        <>
          {/* Coverage Metadata */}
          {coverageReport && (
            <div className="bg-[var(--color-background)] rounded-lg p-4" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
              <div className="flex flex-wrap items-center gap-4 text-sm" style={{ color: 'var(--color-text-secondary)' }}>
                <span>
                  Period: {new Date(coverageReport.periodFrom).toLocaleDateString()} - {new Date(coverageReport.periodTo).toLocaleDateString()}
                </span>
                <span>•</span>
                <span>
                  Generated by: {coverageReport.generatedBy}
                </span>
                <span>•</span>
                <span>
                  {coverageReport.simulationIds.length} simulation(s) analyzed
                </span>
              </div>
            </div>
          )}

          {/* Coverage Overview */}
          <div className="bg-[var(--color-background)] rounded-lg p-6" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
            <h3 className="mb-6 text-center" style={{ color: 'var(--color-text-primary)' }}>Coverage Overview</h3>
            <div className="flex flex-col items-center">
              <div className="relative" style={{ width: '200px', height: '200px' }}>
                {/* Circular Progress */}
                <svg className="transform -rotate-90" viewBox="0 0 200 200" style={{ width: '200px', height: '200px' }}>
                  <circle
                    cx="100"
                    cy="100"
                    r="80"
                    fill="none"
                    stroke="var(--color-surface)"
                    strokeWidth="20"
                  />
                  <circle
                    cx="100"
                    cy="100"
                    r="80"
                    fill="none"
                    stroke={overallCoverage >= 80 ? '#C3E770' : overallCoverage >= 60 ? '#F7EA73' : '#EF6F53'}
                    strokeWidth="20"
                    strokeDasharray={`${(overallCoverage / 100) * 502.4} 502.4`}
                    strokeLinecap="round"
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span style={{ fontSize: '48px', fontWeight: 700, color: 'var(--color-primary)' }}>
                    {overallCoverage.toFixed(1)}%
                  </span>
                </div>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mt-6">
                <div className="text-center">
                  <span
                    className="inline-block px-4 py-2 rounded"
                    style={{ backgroundColor: 'var(--color-surface)', fontSize: '14px', fontWeight: 600, border: '1px solid var(--color-border)', color: 'var(--color-text-primary)' }}
                  >
                    Total Rules: {totalRules}
                  </span>
                </div>
                <div className="text-center">
                  <span
                    className="inline-block px-4 py-2 rounded"
                    style={{ backgroundColor: '#E8F5E9', fontSize: '14px', fontWeight: 600, color: '#1B5E20' }}
                  >
                    Tested: {testedRules}
                  </span>
                </div>
                <div className="text-center">
                  <span
                    className="inline-block px-4 py-2 rounded"
                    style={{ backgroundColor: '#FFEBEE', fontSize: '14px', fontWeight: 600, color: 'var(--color-error)' }}
                  >
                    Untested: {untestedCount}
                  </span>
                </div>
                <div className="text-center">
                  <span
                    className="inline-block px-4 py-2 rounded"
                    style={{ backgroundColor: '#E3F2FD', fontSize: '14px', fontWeight: 600, color: '#0D47A1' }}
                  >
                    Simulations: {coverageReport.totalSimulations || 0}
                  </span>
                </div>
                <div className="text-center">
                  <span
                    className="inline-block px-4 py-2 rounded"
                    style={{ backgroundColor: '#F3E5F5', fontSize: '14px', fontWeight: 600, color: '#4A148C' }}
                  >
                    Scenarios: {coverageReport.totalScenarios || 0}
                  </span>
                </div>
                <div className="text-center">
                  <span
                    className="inline-block px-4 py-2 rounded"
                    style={{ backgroundColor: '#FFF3E0', fontSize: '14px', fontWeight: 600, color: '#E65100' }}
                  >
                    Avg Exec: {(coverageReport.avgRuleExecutions || 0).toFixed(1)}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Coverage Heatmap */}
          {heatmapData.length > 0 && (
            <div className="bg-[var(--color-background)] rounded-lg p-6" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
              <h3 className="mb-4" style={{ color: 'var(--color-text-primary)' }}>Coverage Heatmap (Top 10 Rules)</h3>
              <div className="space-y-3">
                {heatmapData.map((item, index) => {
                  const ruleData = coverageReport?.ruleCoverage?.find(r => r.ruleName === item.rule);
                  return (
                    <div
                      key={index}
                      className="flex items-center justify-between p-4 rounded"
                      style={{ backgroundColor: 'var(--color-surface)', border: '1px solid var(--color-border)' }}
                    >
                      <div className="flex-1">
                        <div className="flex flex-col">
                          <span style={{ fontSize: '14px', fontWeight: 500, fontFamily: 'monospace', color: 'var(--color-text-primary)' }}>
                            {item.rule}
                          </span>
                          {ruleData?.ruleDescription && (
                            <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', marginTop: '4px' }}>
                              {ruleData.ruleDescription}
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <div className="w-48 h-6 rounded overflow-hidden border" style={{ borderColor: 'var(--color-border)', backgroundColor: 'var(--color-background)' }}>
                          <div
                            className="h-full transition-all"
                            style={{
                              width: `${Math.min((item.hits / 50) * 100, 100)}%`,
                              backgroundColor: item.color,
                            }}
                          ></div>
                        </div>
                        <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', width: '60px' }}>
                          {item.hits} hits
                        </span>
                        <span
                          className="inline-block px-3 py-1 rounded-full"
                          style={{
                            backgroundColor:
                              item.status === 'covered' ? '#C3E770' :
                              item.status === 'low' ? '#F7EA73' : '#EF6F53',
                            color:
                              item.status === 'covered' ? '#1B5E20' :
                              item.status === 'low' ? '#5D4037' : '#FFFFFF',
                            fontSize: '12px',
                            fontWeight: 500,
                            width: '100px',
                            textAlign: 'center',
                          }}
                        >
                          {item.status === 'covered' ? '✅ Covered' : item.status === 'low' ? '⚠️ Low' : '❌ Untested'}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Untested Rules */}
          {untestedRules.length > 0 && (
            <div className="bg-[var(--color-background)] rounded-lg p-6" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
              <div className="flex justify-between items-center mb-4">
                <h3 style={{ color: 'var(--color-text-primary)' }}>Untested Rules ({untestedRules.length})</h3>
                <button
                  onClick={() => onNavigate('scenario-editor')}
                  className="flex items-center gap-2 px-4 py-2 bg-[var(--color-accent)] text-white rounded hover:bg-[#FC7857] transition-colors"
                  style={{ fontSize: '14px', fontWeight: 500 }}
                >
                  <Plus size={18} />
                  Create Scenario
                </button>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b" style={{ borderColor: 'var(--color-border)', backgroundColor: 'var(--color-surface)' }}>
                      <th className="text-left p-4" style={{ fontSize: '14px', fontWeight: 600, color: 'var(--color-primary)' }}>Rule Name</th>
                      <th className="text-left p-4" style={{ fontSize: '14px', fontWeight: 600, color: 'var(--color-primary)' }}>Description</th>
                      <th className="text-left p-4" style={{ fontSize: '14px', fontWeight: 600, color: 'var(--color-primary)' }}>Agenda Group</th>
                    </tr>
                  </thead>
                  <tbody>
                    {untestedRules.slice(0, 10).map((rule, index) => (
                      <tr
                        key={index}
                        className="border-b hover:bg-[var(--color-surface)] transition-colors"
                        style={{ borderColor: 'var(--color-border)' }}
                      >
                        <td className="p-4" style={{ fontSize: '14px', fontWeight: 500, fontFamily: 'monospace', color: 'var(--color-text-primary)' }}>
                          {rule.ruleName}
                        </td>
                        <td className="p-4" style={{ fontSize: '14px', color: 'var(--color-text-secondary)' }}>
                          {rule.ruleDescription || 'No description'}
                        </td>
                        <td className="p-4" style={{ fontSize: '14px', color: 'var(--color-text-secondary)' }}>
                          {rule.agendaGroup || '-'}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {untestedRules.length > 10 && (
                  <div className="p-4 text-center" style={{ fontSize: '14px', color: 'var(--color-text-muted)' }}>
                    ... and {untestedRules.length - 10} more untested rules
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Coverage Trend */}
          {trendData.length > 1 && (
            <div className="bg-[var(--color-background)] rounded-lg p-6" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
              <h3 className="mb-4" style={{ color: 'var(--color-text-primary)' }}>Coverage Trend (Last 30 Days)</h3>
              <ResponsiveContainer width="100%" height={250}>
                <AreaChart data={trendData}>
                  <defs>
                    <linearGradient id="colorCoverage" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#285A84" stopOpacity={0.3} />
                      <stop offset="95%" stopColor="#285A84" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                  <XAxis dataKey="date" stroke="var(--color-text-secondary)" style={{ fontSize: '12px' }} />
                  <YAxis stroke="var(--color-text-secondary)" style={{ fontSize: '12px' }} domain={[0, 100]} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: 'var(--color-surface)',
                      border: '1px solid var(--color-border)',
                      borderRadius: '8px',
                      boxShadow: 'var(--shadow-2)',
                      color: 'var(--color-text-primary)',
                    }}
                    formatter={(value: number) => [`${value.toFixed(1)}%`, 'Coverage']}
                  />
                  <Area
                    type="monotone"
                    dataKey="coverage"
                    stroke="#285A84"
                    strokeWidth={2}
                    fill="url(#colorCoverage)"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          )}

          {/* Actions */}
          <div className="bg-[var(--color-background)] rounded-lg p-6" style={{ boxShadow: 'var(--shadow-1)', border: '1px solid var(--color-border)' }}>
            <h3 className="mb-4" style={{ color: 'var(--color-text-primary)' }}>Export Options</h3>
            <div className="flex flex-wrap gap-3">
              <button
                onClick={handleExportCSV}
                className="flex items-center gap-2 px-6 py-3 border text-[var(--color-primary)] rounded hover:bg-[var(--color-surface)] transition-colors"
                style={{ fontSize: '14px', fontWeight: 500, borderColor: 'var(--color-border)' }}
              >
                <FileText size={18} />
                Export CSV
              </button>
              <button
                onClick={handleExportJSON}
                className="flex items-center gap-2 px-6 py-3 border text-[var(--color-primary)] rounded hover:bg-[var(--color-surface)] transition-colors"
                style={{ fontSize: '14px', fontWeight: 500, borderColor: 'var(--color-border)' }}
              >
                <Download size={18} />
                Export JSON
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
